### ISSUE TITLE
Possible oAuth2 JWT integration?

### ISSUE THREAD

**Issue by affluent-bilby-classifieds** [KilledByAPixel/OS13k#32]
I am interesting in forking this to create a kind of virtual MSP (web standards SOE) service. 

The way I would do it is that the user (or the users admin) creates an account via a web interface. A script on the back-end then fires up docker compose which builds the docker container with the javascript desktop inside it. The user can then login and access their desktop from any supported web browser. The apps will be productivity related such as spreadsheets, word processor, LaTeX, e-mail and IM clients, or custom written JS for the business. As you can now compile C to javascript or web assembly with emscripten there should be no shortage of open source apps that can be ported. For legacy Windows applications they can be run inside docker-wine and connect with node-x11.

I wanted to first setup a authentication and login screen but I am currently quite a novice as a developer. I was learning about react-admin and hasura but now I am doing a Javascript course at TAFE and better quality one on Udemy. 

I can access any Udemy course I like and I am thinking of doing this one [Spring Boot Security and oAuth2 in depth from scratch]( https://www.udemy.com/course/spring-boot-security-and-oauth2/)

If you were to implement authentication yourself would you go down the oAuth2 JWT path?

Thank you

**Comment by KilledByAPixel** [comment]
That sounds amazing, I was thinking something like that would be possible and I'd love to it. I have to be honest though, in this area you may already be more knowledgeable then me. I have no idea how to set it up!

**Comment by affluent-bilby-classifieds** [comment]
Hi Frank,

Thanks for getting back to me. Beautiful project.

I can work start on it this weekend. We are doing a UX design unit in my
course so I can do some mockup screens for account setup and login.

I will drive into the Javascript too. I use a different github account for
TAFE related stuff.

This is an example of what I can write but I hope to get much better.

https://github.com/j354374/fed-scripting/tree/master/portfolio/element-positioning

Best regards,

Chris

**Comment by affluent-bilby-classifieds** [comment]
I just mentioned it to a friend at TAFE and he immediately started creating the login and auth in PHP. I was going to use react myself but he is so close to having it up and running that I'm not going to stop him.

**Comment by KilledByAPixel** [comment]
Sounds awesome, can't wait to see what you two cook up.

**Comment by affluent-bilby-classifieds** [comment]
Please be patient as my JavaScript skills need a lot of work. I will stay in touch. Thank you for everything.
